UKHomeOffice/evw-self-serve

acceptance_tests/features/step_definitions/general.js
acceptance_tests/features/step_definitions/link-sent.js
acceptance_tests/features/update-journey-details.feature
apps/update-journey-details/steps.js
apps/update-journey-details/translations/src/en/pages.json
apps/update-journey-details/views/link-sent.html

Added a `/link-sent` page, which is displayed to customers after requesting a link to the self-service form so that they are able to change their flight details.

EVW-1218 Phase 2: Flight change link sent

---

.travis.yml
acceptance_tests/features/step_definitions/general.js
acceptance_tests/features/update-journey-details.feature
apps/update-journey-details/controllers/arrival-date.js
apps/update-journey-details/controllers/is-this-your-flight.js
apps/update-journey-details/steps.js
apps/update-journey-details/views/is-this-your-flight.html
config/config.js
data/airports.json
data/nationalities.json
lib/flight-lookup.js
mocks/flight/post/details.js
package.json
test/unit/apps/update-journey-details/lib/flight-lookup.spec.js

✈️ ✈️ 
Added flight service so we can now return proper flight data 
Acceptance tests to check for:
- A correct flight then proceeding to declaration page
- An incorrect flight found and returning to enter a different flight number
- A flight which isn't found
Unit tests for the flight lookup module using dyson to mock the api
Added `npm run dev:mock` to start the app and use the mock flight api
✈️ ✈️

EVW-1361 Integration - Make a real call to the flight API

---

acceptance_tests/features/step_definitions/check-your-answers.js
acceptance_tests/features/step_definitions/general.js
acceptance_tests/features/update-journey-details.feature
apps/common/controllers/evw-base.js
apps/find-your-application/controllers/enter-your-details.js
apps/update-journey-details/controllers/departure-date-and-time.js
apps/update-journey-details/fields/departure-date-and-time.js
apps/update-journey-details/steps.js
apps/update-journey-details/translations/src/en/validation.json
apps/update-journey-details/views/check-your-answers.html
lib/formatting.js
test/lib/formatting.spec.js
test/unit/validation/arrival-date.spec.js
test/unit/validation/departure-date.spec.js
validation/arrival-date.js
validation/departure-date.js
validation/departure-time.js

- adds gap between table and `'Confirm details` button
- all form entries are now displayed
- Date formats are now all `'DD-MM-YYYY'` (we can change this at some point if needed but this normalises e.g. arrival date and departure date formats)
- Adds in `lib/formatting` for all our date/time retrieving and parsing needs
- Before it was going to the default of `/confirm`, which is a url we don't supply
- This is done in a slightly hacky way because I couldn't figure out how constructor options were supposed to work 
- instead it hijacks the `getNextStep` method and insert a new `confirmStep` option there

[NIJ] update-journey-details: Show summary data

---

apps/common/controllers/evw-base.js
lib/formatting.js
test/lib/formatting.spec.js

- takes either a time or a date delimited key and then glues values together from other fields

[NIJ] Add Set date times

---

package.json
test/.eslintrc
test/common.js
test/lib/evw-lookup.spec.js
test/unit/apps/update-journey-details/lib/flight-lookup.spec.js

- Allows us to spin up and kill dyson stub serving within the context of the mocha runtime
- This means running e.g. `mocha -w` won't break the second time your tests run due to port collision errors
- It's not the most elegant thing but what is elegance anyway

[NIJ] Spin up/kill dyson programmatically

---

acceptance_tests/features/step_definitions/general.js
acceptance_tests/features/update-journey-details.feature
apps/update-journey-details/controllers/how-will-you-arrive.js
apps/update-journey-details/index.js
apps/update-journey-details/steps.js
apps/update-journey-details/views/confirmation.html
config.js

- uses the same endpoint as for download verifcation, this may be incorrect, will need to catch up with @jackmaloney
- Use query string to pass number/token:
- Params was too confusing with the way that the hmpo wizard wants to handle things
- Now we'll check for the presence of evwNum/token and set to session
- Session checks will occur in the entry url only as subsequent routes will redirect if there's no session established
- TODO tests for query/session checking

[NIJ?] update-journey-details: check valid number/token

---

acceptance_tests/features/smoke/update-journey-details.smoke.feature
acceptance_tests/features/step_definitions/confirmation.js
acceptance_tests/features/step_definitions/update-journey-smoke.js
apps/common/views/error.html
apps/find-your-application/controllers/enter-your-details.js
apps/update-journey-details/controllers/arrival-date.js
apps/update-journey-details/controllers/confirmation.js
apps/update-journey-details/controllers/how-will-you-arrive.js
apps/update-journey-details/translations/src/en/pages.json
config.js
errors/index.js
package.json
test/apps/update-journey-details/controllers/confirmation.spec.js

- Updates `evw-integration-stub` to latest to pick up `update` endpoint
- Sends mapped subset of user information to integration service using `propMap`
- Quick test for propMap
- adds email address and reference number brought back from integration service
- Calls to integration service but does not save to customer db yet
- adds small amount of additional styling to render teal confirmation box
- Checks for the presence of confirmation number (of fixed length, but allows it to be any string of length === 8)
- `emailAddress` and `updateNumber` now added to the `req` so we can manually clear the session (as per issue noted here: https://github.com/UKHomeOffice/global-entry-customer/blob/master/apps/global-entry/controllers/complete.js#L22-L30)
- If we get an error in the app the user was …

[NIJ] Add update-journey-details smoke test 🚭

---

acceptance_tests/features/step_definitions/update-journey-smoke.js

- Allows background test to pass
- Bit of a hack in the assertions but works for letting us know whether a case was added or not

[NIJ] Remove callback from smoke test background

---

acceptance_tests/features/find-your-application.feature
apps/find-your-application/controllers/enter-your-details.js
apps/find-your-application/steps.js
apps/find-your-application/translations/en/default.json
apps/find-your-application/translations/src/en/pages.json
package.json
test/lib/evw-lookup.spec.js
test/validation/evw-number.spec.js
validation/evw-number.js

- Adds in page for 'not yet verified'
- keeps expired
- other errors display in validation summary
- updates `evw-integration-stub` to get new error codes
- adds acceptance tests for various failure states

[EVW-1449] Additional lookup errors for finding evw

---

apps/update-journey-details/fields/arrival-date.js
validation/departure-time.js

Set `arrival-date` to have `type: ['date']` so it is treated as a HOF date and saved in the model correctly. The departure date and time fields will then be validated with the arrival date properly.
Simplified the departure date and time validation by removing some of the `moment` objects.

EVW-1442 No validation on departure date

---

acceptance_tests/features/find-your-application.feature
apps/find-your-application/controllers/enter-your-details.js
apps/find-your-application/controllers/link-sent.js
apps/find-your-application/steps.js
apps/find-your-application/translations/src/en/pages.json
apps/find-your-application/views/link-sent.html

The verify EVW successful response now contains the user's email address so we need to save it and display it on the `/link-sent` page.

EVW-1472 Check your email page add email address

---

test/validation/arrival-date.spec.js
validation/arrival-date.js

Improve the check that the arrival date and time is not within 48 hours of the date and time now
- Add the current time to the arrival time so we can get a better comparison
- Change the comparison granularity from the default (milliseconds) to seconds
- Improve the unit tests so they pass a string into the validation rather than a moment object
Scenario...If an arrival date of 2 days time is entered for a flight which has an arrival time later than the time now then this is outside the 48 hour window and should be valid.
**Before**
**After**

EVW-1477 Validation defect for journey update in 2 days time 

---

acceptance_tests/features/validation.feature
apps/update-journey-details/fields/departure-date-and-time.js
apps/update-journey-details/translations/src/en/validation.json

The `departure-date` field is required and if the user tried to proceed without entering it then an error would show without a message. This adds the message.
**Before**
**After**

EVW-1478 No 'required' validation message for departure date

---

acceptance_tests/features/validation.feature
apps/find-your-application/translations/src/en/validation.json

**Change 'numeric' error message**
HOF currently treats the date 00-00-0000 as non-numeric so we need an error message that makes sense for both 12-!!-1987 and 00-00-0000.
**Before**
**After**

EVW-1484 Ambiguous  error message is displayed when an invalid DOB is entered.

---

apps/common/views/layout.html

Changed feedback link mailto and subject from the default HOF example ones to ones that are more useful for our users.
**Before**
**After**

EVW-1506 Beta feedback link

---

apps/update-journey-details/translations/src/en/fields.json
apps/update-journey-details/translations/src/en/pages.json
apps/update-journey-details/views/flight-number.html
assets/scss/_hof_overrides.scss
assets/scss/app.scss
assets/scss/panels.scss

- Form hint styling
- Not bold
- Black
- Form control styling
- Darker grey
- Thicker border width
- Change padding back to default
- Flight number page styling
- Removed the call-out text and added as a form hint
- Two form hints needed so added html into the label instead of using default form hint
- Moved the help panel above the submit button
- Increased the gap between the help panel and the submit button
- Decreased the width of the flight number field
**Before**
**After**

EVW-1515 Update flight details styling - new flight number page

---

apps/update-journey-details/views/arrival-date.html

This improves the display of the left red border for errors as the top of the border is now inline with the field label

EVW-1516 Update flight details styling - date of arrival page

---

apps/update-journey-details/controllers/arrival-date.js
test/lib/flight-lookup.spec.js
test/validation/arrival-date.spec.js
validation/arrival-date.js

- Use the arrival time in the validator instead of the current time
- Use process function instead of saveValues function to get flight details earlier in the stack so we can validate using the arrival time
- Change unit tests to mock the model
- Minor formatting improvements
- Move the flight-lookup unit tests into the correct directory

EVW-1531 Self serve Date time arrival validation

---

acceptance_tests/features/step_definitions/check-your-answers.js
acceptance_tests/features/step_definitions/general.js
acceptance_tests/features/step_definitions/update-journey-smoke.js
acceptance_tests/features/update-journey-details.feature

- instead of hardcoding e.g. `"10-08-2016"` we can now pass in future amounts
- e.g. `"2 months" in the "future"`
- changes all instances of both adding and expecting dates to be future expectations
We're going to check for future dates in an increasingly large number of places so `general` seems to be correct
- Wrap each string we check in a matcher
- Quite a specific pattern to match
- `'${"amount unit" in the "direction"}'`
- e.g. `'${"2 months" in the "future"}'`

[NIJ] Acceptance test dates in the future

---

acceptance_tests/features/find-your-application.feature
apps/find-your-application/steps.js
apps/find-your-application/translations/src/en/pages.json
apps/find-your-application/views/update-limit-reached.html
package.json
test/lib/evw-lookup.spec.js

- Added `/update-limit-reached` page to display to the user if they try to update their application more than twice.
- Added acceptance tests to check that the page is correctly displayed in this scenario.
- Fixed unit test which checks the value that is returned when an EVW is found successfully...it now returns an email address instead of a success flag.

EVW-1538 User self service error page - Number of flight changes

---

acceptance_tests/features/step_definitions/general.js
apps/update-journey-details/controllers/arrival-date.js
apps/update-journey-details/steps.js
lib/flight-lookup.js
mocks/flight/post/details.js
test/lib/flight-lookup.spec.js

- Departures now always returned as a list
- `mapDepartures` takes a response from the `flight-forecast-service` and maps it to form values e.g. `inwardDepartureCountryPlane` etc
- mock updated to pass back a list
- Should allow us a quick release of the app whilst we work on getting the departures-check interstitial page completed
- Should operate as before, but subscribes to new model of multiple departures
Next step will be to ship a new `check-departures` interstitial page

[EVW-1619] Multi-departures pt I: Expect a list of departures

---

acceptance_tests/features/step_definitions/general.js
acceptance_tests/features/update-journey-details.feature
apps/update-journey-details/controllers/arrival-date.js
apps/update-journey-details/controllers/choose-departure-airport.js
apps/update-journey-details/fields/choose-departure-airport.js
apps/update-journey-details/fields/index.js
apps/update-journey-details/steps.js
apps/update-journey-details/translations/src/en/fields.json
apps/update-journey-details/translations/src/en/pages.json
apps/update-journey-details/translations/src/en/validation.json
apps/update-journey-details/views/choose-departure-airport.html
mocks/flight/post/details.js
test/apps/update-journey-details/controllers/choose-departure-airport.spec.js
test/lib/flight-lookup.spec.js

###	Swaps mock flight number: LEG0001 => BA0072
- Should mean multileg departure sections can be tested against the stubs and the deployed `flight-forecast-service`
- same as with `evw-customer` app [changes](https://github.com/UKHomeOffice/evw-customer/commit/0f3b6967a3254683b30ae4e886d51865794918c5)
- Nasty hack to add in flight number (but how to edit the legend prop inside locals without lots of locals manipulation?)
- 'legend' field of departures left as single space string 😢 
- `process` picks the departure from departures array using `.find`
- Adds test for `locals` and `process` methods
- Adds 'exact' matcher for ID clicking in `general.js` for when you need to click something with a `'weird-ID'`
- Strimmed down version of happy path, checking for a small subset of usual …

[EVW-1619] display multiple departure options page

---

config.js
lib/logger.js

Changed logging output so it's compatible with Kibana.
For example:
`[EVW Self Serve] [INFO] 2016-09-05T09:31:31.683Z status=200, method=GET, url=/update-journey-details/arrival-date, response_time=10, content_length=8617`
`[EVW Self Serve] [INFO] 2016-09-05T09:31:32.957Z looking up flight: number=KU0101, date=2016-09-09`
`[EVW Self Serve] [INFO] 2016-09-05T09:31:32.968Z flight service response for { number: 'KU0101', date: '2016-09-09' }: flights=[flightNumber=KU0101, departures=[port=DXB, country=AE], arrival=[port=LGW, date=2016-09-09, time=1845], body=[flightNumber=KU0101, arrivalDate=2016-09-09]]`

EVW-1622 Add logstashforwarder entries for `evw-customer` and `evw-self-serve`

---

.travis.yml

Our rpm jobs will look to the releases branch rather than master now, hopefully meaning we can have versions in our released app! :-/
- Changes `travis.yml` to deploy (hopefully) to github only from master builds
- So, er, this build should not end up on the [`releases`](https://github.com/UKHomeOffice/evw-self-serve/releases) branch of github, hopefully 😅

[NIJ] Only publish releases of master

---

acceptance_tests/features/smoke/update-journey-details.smoke.feature
acceptance_tests/features/step_definitions/check-your-answers.js
acceptance_tests/features/step_definitions/general.js
acceptance_tests/features/update-journey-details.feature
acceptance_tests/features/validation.feature
apps/update-journey-details/controllers/check-your-answers.js
apps/update-journey-details/controllers/confirmation.js
apps/update-journey-details/fields/index.js
apps/update-journey-details/fields/return-travel.js
apps/update-journey-details/fields/uk-departure.js
apps/update-journey-details/steps.js
apps/update-journey-details/translations/src/en/fields.json
apps/update-journey-details/translations/src/en/pages.json
apps/update-journey-details/translations/src/en/validation.json
apps/update-journey-details/views/check-your-answers.html
apps/update-journey-details/views/return-travel.html
apps/update-journey-details/views/uk-departure.html
package.json
test/apps/update-journey-details/controllers/check-your-answers.spec.js
test/apps/update-journey-details/controllers/confirmation.spec.js
test/fixtures/update-model.js

Ask the user if their return travel details have changed and re-capture these details if necessary.
These questions have been added at the end of the form, just after asking for their flight departure details.
* Have your travel details for your departure from the UK changed?
* Do you have your travel details for your departure from the UK?
* If yes, ask for travel number, departure date and port
* If no, ask for duration
* Display the relevant answers on the check your answers page
Send these new details to Integration Service along with the rest of the update.
**New travel details changed question**
**If user knows their travel details, they must fill them in here**
**If they don't know their travel details, they must select a duration**
**Updated check your answers page**

Feature/EVW-1977 UK departure details

---

apps/update-journey-details/controllers/flight-number.js
apps/update-journey-details/steps.js
apps/update-journey-details/views/check-your-answers.html
test/apps/update-journey-details/controllers/flight-number.spec.js

Allow departure date to be edited separately to flight number
Setting `is-this-your-flight` to null when changing flight number.
* if a user tries to edit the flight number, but then go back on the browser to the check your answers page and try to submit the update, it will fail
* this is preferable to submitting an incorrect flight number

Correct behaviour for editing flight number

---

apps/update-journey-details/controllers/is-this-your-flight.js
test/apps/update-journey-details/controllers/is-this-your-flight.spec.js

If the users says 'No' this is not their flight and then clicks back in the browser, this will happen:
This fix sends the user back to the `flight-number` step if no flight details are found in the session.

Bugfix/NIJ - prevent empty flight details submission

---

apps/common/controllers/evw-base.js
apps/update-journey-details/fields/departure-date.js
apps/update-journey-details/fields/uk-departure.js
test/apps/common/controllers/evw-base.spec.js

The issue was caused by the arguments given to custom validators only being run at startup, not whenever the validators are used.
This is fixed by doing the following:
* check if argument for custom validator is a function, in `evw-base.js` `validateField` function
* if it's a function, run it and pass the result to the validator function
* otherwise, just pass the value to the validator function
* fixing all uses of the `beforeDate` and `afterDate` custom validators

EVW-2191 Fixing travel within 3 months failing validation

---

.npmrc
.travis.yml
acceptance_tests/features/update-journey-details.feature
apps/update-journey-details/controllers/how-will-you-arrive.js
package.json

Strip `?hof-cookie-check` from token URL param
* this is causing an issue due to breaking schema validation at the end of the update application
* the token was too long, because it was appended with `?hof-cookie-check`
Also fixing acceptance tests for new flight schedule and making this work on travis with the open source `evw-schemas`

[NIJ] remove cookie check from token

---

README.md

Requires full url the first time you go to the page and saves it to your cookies so next time you don't need to go to the full path
http://localhost:8080/update-journey-details/how-will-you-arrive?evwNumber=valid&token=token

Readme - fix - url for update-journey

---

apps/update-journey-details/translations/src/en/pages.json

- An organisation change means that email addresses @homeoffice.gsi.gov.uk are changing to @homeoffice.gov.uk
- This chnage is already live so we need to change systems to reflect the change so that gsi can be decommissioned.

DPS-1649 Change all emails to refer to homeoffice.gov.uk 

---

config.js
lib/session/mongo.js
test/lib/session/mongo.spec.js

https://jira.digital.homeoffice.gov.uk/browse/DPS-1672
Our recent weird session issues on UAT with EVW Self Serve were triggered by me putting the incorrect path on an image.
Instead of using `{{assetPath}}/images` to point to EVW Self Serve’s image folder, I pointed the image to `/public/images`, which is EVW Customer’s image location.
EVW Customer happily served up this image, and set a `connect.sid` session cookie at the same time. This overwrote EVW Self Serve’s `connect.sid` session cookie (because both apps are hosted on the same domain), meaning EVW Self Serve lost its session.
The image [has been pointed to the right place](https://github.com/UKHomeOffice/evw-self-serve/commit/761d4cd26096b60503ee1f1fa5b815eba831b350), but it unsurprisingly took a long time for us to work out that …

WIP: DPS-1672: prevent session issues
