- .travis.yml
Adds in notifications for all levels of build
Can be modified as per https://docs.travis-ci.com/user/notifications/ if we find it's a bit too loud
> Add slack notifications from travis

- acceptance_tests/features/update-journey-details.feature
- apps/update-journey-details/fields/flight-number.js
- apps/update-journey-details/fields/index.js
- apps/update-journey-details/steps.js
- apps/update-journey-details/translations/src/en/fields.json
- apps/update-journey-details/translations/src/en/pages.json
- apps/update-journey-details/translations/src/en/validation.json
- apps/update-journey-details/views/flight-number.html
> EVW-1300 Phase 2 - your new flight number

- acceptance_tests/features/step_definitions/general.js
- acceptance_tests/features/update-journey-details.feature
- apps/update-journey-details/fields/arrival-date.js
- apps/update-journey-details/fields/index.js
- apps/update-journey-details/steps.js
- apps/update-journey-details/translations/src/en/fields.json
- apps/update-journey-details/translations/src/en/pages.json
- apps/update-journey-details/translations/src/en/validation.json
- apps/update-journey-details/views/arrival-date.html
Added `/arrival-date` page so users can change their arrival date.
> EVW-1301 Phase 2 - new arrival date

- package.json
- 1.1.0 breaks the build for us
> pin cucumber to 1.0.0

- acceptance_tests/features/step_definitions/general.js
- acceptance_tests/features/update-journey-details.feature
- apps/update-journey-details/controllers/arrival-date.js
- apps/update-journey-details/controllers/is-this-your-flight.js
- apps/update-journey-details/fields/arrival-date.js
- apps/update-journey-details/fields/index.js
- apps/update-journey-details/fields/is-this-your-flight.js
- apps/update-journey-details/steps.js
- apps/update-journey-details/translations/src/en/fields.json
- apps/update-journey-details/translations/src/en/pages.json
- apps/update-journey-details/translations/src/en/validation.json
- apps/update-journey-details/views/is-this-your-flight.html
- assets/scss/app.scss
Added `/is-this-your-flight` page so users can check that their flight details are correct.
Flight details are hardcoded until the flight api has been added.
> EVW-1221 Phase 2: Flight API happy path

- acceptance_tests/features/step_definitions/general.js
- acceptance_tests/features/validation.feature
- apps/update-journey-details/fields/enter-your-details.js
- apps/update-journey-details/steps.js
- apps/update-journey-details/translations/src/en/validation.json
- Adds in some validtion around the dob field
- can't be in the future
- must be numeric
- strict "YYYY" format validation for year `dob-year` field
- Adds very brief validation acceptance feature
> Add in date validation for dob

- .travis.yml
I'm not at work 🙈  but if I was, I would issue this PR to get our travis jobs green again
> [NIJ] Only spin up mock during acceptance tests

- acceptance_tests/features/step_definitions/check-your-answers.js
- acceptance_tests/features/step_definitions/general.js
- acceptance_tests/features/update-journey-details.feature
- apps/common/controllers/evw-base.js
- apps/find-your-application/controllers/enter-your-details.js
- apps/update-journey-details/controllers/departure-date-and-time.js
- apps/update-journey-details/fields/departure-date-and-time.js
- apps/update-journey-details/steps.js
- apps/update-journey-details/translations/src/en/validation.json
- apps/update-journey-details/views/check-your-answers.html
- lib/formatting.js
- test/lib/formatting.spec.js
- test/unit/validation/arrival-date.spec.js
- test/unit/validation/departure-date.spec.js
- validation/arrival-date.js
- validation/departure-date.js
- validation/departure-time.js
> Show summary data again

- acceptance_tests/features/step_definitions/general.js
- acceptance_tests/features/update-journey-details.feature
- apps/update-journey-details/controllers/arrival-date.js
- apps/update-journey-details/controllers/confirmation.js
- apps/update-journey-details/controllers/flight-not-found.js
- apps/update-journey-details/controllers/how-will-you-arrive.js
- apps/update-journey-details/steps.js
- apps/update-journey-details/views/check-your-answers.html
- lib/flight-lookup.js
- test/apps/update-journey-details/lib/flight-lookup.spec.js
- test/fixtures/update-model.js
- Arrival date wasn't being saved correctly
- modifies formatting in `flight-lookup` to conform with `departure-date`
- no more `/edit/` in the edit links (would 404)
- blitz flight information on every lookup
- get rid of flight info from model when flight-not-found
- add `next` step to not found step in order that user can continue to retry without being kicked back to the start of the journey (without params aghr!)
Fixes [EVW-1448](https://jira.digital.homeoffice.gov.uk/browse/EVW-1448?filter=12754)
Fixes [EVW-1432](https://jira.digital.homeoffice.gov.uk/browse/EVW-1432?filter=12754)
Fixes [EVW-1440](https://jira.digital.homeoffice.gov.uk/browse/EVW-1440?filter=12754)
Fixes [EVW-1433](https://jira.digital.homeoffice.gov.uk/browse/EVW-1433?filter=12754)
> [EVW-1432] Keep arrival date in the model

- .gitignore
- acceptance_tests/features/update-journey-details.feature
- apps/common/translations/en/default.json
- apps/common/translations/src/en/errors.json
- apps/common/views/404.html
- apps/find-your-application/translations/en/default.json
- config.js
- middleware/not-found.js
* fixes funky title
* add default `appPath` to config
> Adding correct content to 404 page

- acceptance_tests/features/page-not-found.feature
- acceptance_tests/features/step_definitions/page-not-found.js
- apps/common/views/404.html
* check it renders with the correct title
* check the start again link takes user to enter your details page
> Adding acceptance test for 404 page

- acceptance_tests/features/update-journey-details.feature
- apps/update-journey-details/controllers/departure-date-and-time.js
- apps/update-journey-details/views/departure-date-and-time.html
- Correctly display the user's flight number and departure airport on the `departure-date-and-time` page according to the details they enter each time they go through the flight path.
- Added acceptance tests to check these values are correctly set.
> EVW-1461 Dynamic text not changing 

- build_rpm.sh
Copy validation rules into the fpm build directory so our custom validation will work
> NIJ - Copy validation rules into the fpm build directory

- README.md
- apps/common/translations/src/en/app.json
- apps/common/views/cookies.html
- package.json
> NIJ - Change more instances of wavier to waiver

- apps/update-journey-details/fields/arrival-date.js
- apps/update-journey-details/translations/src/en/validation.json
Added missing 'required' validation message for the `arrival-date` field.
> NIJ - Add missing 'required' validation for arrival date

- apps/update-journey-details/views/check-your-answers.html
https://jira.digital.homeoffice.gov.uk/browse/EVW-1497
> EVW-1497 Add classes to summary elements for end to end test

- acceptance_tests/features/update-journey-details.feature
- apps/update-journey-details/views/confirmation.html
- Hide page title
- Emphasise text say that the user needs to bring the printed EVW with them
**Before**
**After**
> EVW-1504 Content changes to self service summary page

- apps/common/views/layout.html
- apps/common/views/partials/back.html
- apps/find-your-application/views/enter-your-details.html
- apps/find-your-application/views/evw-expired.html
- apps/find-your-application/views/evw-not-verified.html
- apps/find-your-application/views/link-sent.html
- apps/update-journey-details/steps.js
- apps/update-journey-details/views/arrival-date.html
- apps/update-journey-details/views/check-your-answers.html
- apps/update-journey-details/views/confirmation.html
- apps/update-journey-details/views/declaration.html
- apps/update-journey-details/views/departure-date-and-time.html
- apps/update-journey-details/views/email-us.html
- apps/update-journey-details/views/flight-not-found.html
- apps/update-journey-details/views/flight-number.html
- apps/update-journey-details/views/how-will-you-arrive.html
- apps/update-journey-details/views/is-this-your-flight.html
Removed the back button and steps from view templates.
> EVW-1486 Unnecessary breadcrumb in self-service

- apps/update-journey-details/views/is-this-your-flight.html
- assets/scss/app.scss
Removed bold formatting from flight details check values.
> EVW-1491 Content formatting bold instead of plain

- app.js
- apps/common/views/partials/gatag.html
- config.js
Enable Google Analytics tracking code
> EVW-1509 Google analytics

- apps/update-journey-details/translations/src/en/fields.json
- assets/scss/_hof_overrides.scss
- Add flight number hint text
- Bold hint text styling
> EVW-1493 Content - Your new flight details page

- assets/scss/_hof_overrides.scss
Improved form hint styling to include more form hints
> NIJ - Improved form hint styling to include more form hints

- apps/update-journey-details/views/departure-date-and-time.html
- apps/update-journey-details/views/flight-number.html
- assets/scss/app.scss
- assets/scss/panels.scss
This improves the display of the left red border for errors as the top of the border is now inline with the field label.
> EVW-1519 Update flight details styling - date/time leave country of origin page

- apps/find-your-application/fields/enter-your-details.js
- apps/update-journey-details/views/flight-number.html
- assets/scss/app.scss
- assets/scss/panels.scss
- Added margin-top to submit button
- Remove margin-top from date form groups
- Removed date of birth 4 digit year validation. 4 digit year validation is not displaying error messages correctly so we'll probably need to implement this with custom validation. This would also mean we could check dates are correct, which is something HOF doesn't do.
> EVW-1513 Update flight details styling - enter your details page

- assets/scss/app.scss
> EVW-1518 Update flight details styling - is this your flight page

- apps/common/views/partials/gatag.html
Google analytics modifications to enable goal tracking
> EVW-1532 Incorrect GA analytics on self serve

- apps/common/translations/src/en/buttons.json
- apps/update-journey-details/views/check-your-answers.html
- assets/scss/app.scss
- Bolded data values
- Changed column width to give data labels more room
- Changed Edit button text from 'Change' to 'Edit'
- Made Edit button box-shadow less dark
- Increased text size from 16px to 19px
> EVW-1520 Update flight details styling - check your answers page

- assets/scss/app.scss
Reduce the top and bottom margins on the checkbox
> EVW-1521 Update flight details styling - declaration page

- apps/update-journey-details/views/confirmation.html
- assets/scss/app.scss
- Remove hr above the Finish button
- Reduce space above the Finish button
> Improve confirmation page styling

- acceptance_tests/features/find-your-application.feature
- acceptance_tests/features/validation.feature
- apps/find-your-application/translations/src/en/validation.json
- apps/update-journey-details/translations/src/en/validation.json
Updated various validation messages.
> EVW-1525 Content: update self service error messages

- apps/update-journey-details/views/arrival-date.html
- apps/update-journey-details/views/departure-date-and-time.html
- assets/scss/_hof_overrides.scss
- Revert markup back to fieldsets and improve styling with CSS instead
> NIJ - Improve fieldset markup

- acceptance_tests/features/validation.feature
Change hardcoded date to a dynamic one so we don't get more randomly failing tests at some point in the future.
> NIJ - Change hardcoded date to a dynamic one

- package.json
**Moves the error messages below the field label.**
> Upgrade to hof 8.1.0

- acceptance_tests/features/update-journey-details.feature
- apps/update-journey-details/translations/src/en/pages.json
- apps/update-journey-details/views/flight-not-found.html
- assets/scss/panels.scss
Changed content and ordering of the `/flight-not-found` page.
> EVW-1517 Update content on /flight-not-found

- apps/common/controllers/evw-base.js
- apps/update-journey-details/translations/src/en/validation.json
- test/validation/departure-time.spec.js
- validation/departure-time.js
Add validation to the departure date and time to check that they are not within the next 48 hours.
> EVW-1621 Validation departure date and time

- acceptance_tests/features/update-journey-details.feature
- apps/update-journey-details/controllers/choose-departure-airport.js
- apps/update-journey-details/translations/src/en/fields.json
- apps/update-journey-details/views/choose-departure-airport.html
- test/apps/update-journey-details/controllers/choose-departure-airport.spec.js
- allows us to use the fields.json inside our template mixins as intended
- removes cruft from controller and view
- acceptance test time change based on moment's changing behaviour (in the future, the time will be earlier!)
> [NIJ] Pass FLIGHT_NUMBER directly into fields.json

- app.js
- We weren't publishing the version of our application, this should fix it
> [NIJ] Add healthcheck/version endpoint 💉

- app.js
- errors/index.js
- this is a bit dumb, but depending on context (performance platform, internal, HA-Proxy backend rules, versions dashboard etc) we will want the same information back from different endpoints
- should eventually be changed to a single endpoint imo, but that will take lots of strategic chat
- fixes issue of rendering an error breaking when we didn't have a session available
> [NIJ] publish version on multiple endpoints

- lib/flight-lookup.js
- test/lib/flight-lookup.spec.js
https://jira.digital.homeoffice.gov.uk/browse/EVW-1574
- The flight number is now converted to uppercase so it is consistent with the customer app
> EVW-1574 Self serve flight number to upper case

- .travis.yml
* add space before & for run in background
> Amending travis config to fix build

- apps/update-journey-details/controllers/departure-date.js
- mocks/flight/get/details.js
- test/apps/update-journey-details/controllers/departure-date.spec.js
This is the same as https://github.com/UKHomeOffice/evw-customer-hof/pull/261
> EVW-2177 Reject domestic flights from flight service

- apps/update-journey-details/controllers/departure-date.js
- test/apps/update-journey-details/controllers/departure-date.spec.js
- Adds the function and uses it!
- Means that departure date validation should be called every time we ask for a validation (GOOD), rather than drawing on the in memory calculation (BAD)
- should fix issues with cached calculations about the future (errant) [2228](https://jira.digital.homeoffice.gov.uk/browse/EVW-2228)
> [EVW-2228] Add 'getTravelDates' to departure-date controller

- package.json
for use of node/chrome debugging tools
> Add inspect npm script

- .travis.yml
as per what we run on our servers
> Test node 6 only for travis

- acceptance_tests/features/find-your-application.feature
- apps/find-your-application/translations/src/en/pages.json
https://jira.digital.homeoffice.gov.uk/browse/DPS-1627
> DPS-1627: fix text on Find Your Application link-sent screen

- apps/common/views/layout.html
migrating away from .gsi domain
> migrating from .gsi

- app.js
- apps/common/views/partials/gatag.html
- assets/js/typeahead/init-typeahead.js
- assets/js/typeahead/typeahead.jquery.js
- config.js
- package.json
https://github.com/UKHomeOffice/registered-traveller-customer/pull/1044
> DPS-1981: GOV.UK cross-domain Google Analytics

- data/airports.json
Adds Berlin Brandenburg Airport
> Adding Berlin Airport

- apps/common/views/partials/gatag.html
> DPS498 - Adding GA secure cookie flag

- apps/update-journey-details/controllers/train-date-of-departure.js
Using older HOF forms error class, following the example in the departure date controller https://github.com/UKHomeOffice/evw-self-serve/blob/5d9a6617117aa8b8320d32b888aa627327e9d9f8/apps/update-journey-details/controllers/departure-date.js#L98
> Using correct error class

- apps/find-your-application/translations/src/en/pages.json
https://collaboration.homeoffice.gov.uk/jira/browse/DPSPS-702
> 48 hour text change
